// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs defs.go

package goutmp

type (
	TimeVal	struct {
		Sec	int64
		Usec	int64
	}
	ExitStatus	struct {
		Termination	int16
		Exit		int16
	}
	Utmpx	struct {
		Type		int16
		Pid		int32
		Line		[32]int8
		Id		[4]int8
		User		[32]int8
		Host		[256]int8
		Exit		ExitStatus
		Session		int32
		Tv		TimeVal
		Addr_v6		[4]uint32
		X_dummy		[20]int8
		Pad_cgo_0	[4]byte
	}
)

const (
	_T_EMPTY		= 0x0
	_T_USER_PROCESS		= 0x7
	_T_INIT_PROCESS		= 0x5
	_T_LOGIN_PROCESS	= 0x6
	_T_DEAD_PROCESS		= 0x8
)
