// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs defs.go

package goutmp

type (
	TimeVal	struct {
		Sec	int64
		Usec	int64
	}
	ExitStatus	struct {
		Termination	int16
		Exit		int16
	}
	Utmpx	struct {
		Type		int16
		Pid		int32
		Line		[32]int8
		Id		[4]int8
		User		[32]int8
		Host		[256]int8
		Exit		ExitStatus
		Session		int32
		Tv		TimeVal
		Addr_v6		[4]uint32
		X_dummy		[20]int8
		Pad_cgo_0	[4]byte
	}
)

const (
	EMPTY		= 0x0
	BOOT_TIME	= 0x2
	OLD_TIME	= 0x4
	NEW_TIME	= 0x3
	USER_PROCESS	= 0x7
	INIT_PROCESS	= 0x5
	LOGIN_PROCESS	= 0x6
	DEAD_PROCESS	= 0x8

	UTMPS_UT_LINESIZE	= 0x20
	UTMPS_UT_NAMESIZE	= 0x20
	UTMPS_UT_HOSTSIZE	= 0x100
	UTMPS_UT_IDSIZE		= 0x4
)
